#!/bin/bash
# 用来爬各学院通知的地址
# Perl modules
cpan install Mojolicious
# set up minimal environment
mkdir -pv lib/Scripts
pushd lib/Scripts
wget https://github.com/tusooa/scripts/raw/servant/lib/Scripts/Base.pm
wget https://github.com/tusooa/scripts/raw/servant/lib/Scripts/WindowsSupport.pm
wget https://github.com/tusooa/scripts/raw/servant/lib/Scripts/scriptFunctions.pm
popd
# run
perl -Ilib ./update-notification-group.perl
