#!/bin/bash
: <<'EOF'
    Copyright (C) 2018 Herald Studio

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
EOF
# 用来爬课表
# Perl modules
cpan install Mojolicious
# set up minimal environment
mkdir -pv lib/Scripts
pushd lib/Scripts
wget https://github.com/tusooa/scripts/raw/servant/lib/Scripts/Base.pm
wget https://github.com/tusooa/scripts/raw/servant/lib/Scripts/WindowsSupport.pm
wget https://github.com/tusooa/scripts/raw/servant/lib/Scripts/scriptFunctions.pm
popd
# run
perl -Ilib ./fetch-classes.perl
